---
title: "Estudo função de dispersão na simulação neutra coalescente"
author: "Mori, Danilo Pereira"
date: "3 de abril de 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introdução ##

Os modelos neutros de campo médio apresentam dois parâmetros para descrever a distribuição de abundãncia de espécies (SAD): theta e m (Hubbell 2001, Etienne 2005). Já o modelo neutro de espaço explícito coalescente depende de dois parâmetros: U (taxa de especiação na paisagem) e *d* (distância média de dispersão dos indivíduos na metacomunidade) (Rosindell et al 2008).

Theta é o chamado número fundamental da biodiversidade, número adimensional que pode ser descrita como a relação entre o número de indivíduos($J_{M}$) e da taxa de especiação da netacomunidade (U): $\theta = 2J_{M}U$ (Hubbell 2001). Assim, se $\theta = 50$, então, "o produto de duas vezes o tamanaho da metacounidade e a taxa de especiação (novas espécies por evento de nascimento na metacomunidade) é igual 50 novas espécies por geração" (Ricklefs 2012). Considerando a metacomunidade como uma paisagem finita composta de habitat e não habitat e saturada (todas as unidades de habitat estão colonizadas antes do evento de morte - *zero-sum assumption*), podemos escrever $\theta$ como:

$$\theta = 2Ap DA_{media} U  $$

Onde $DA_{media}$ = densidade media de indivíduos na paisagem (ind./ha), p = porcentagem de cobertura vegetal da paisagem (# unidades de habitat/ # total de unidades na paisagem [REESCREVER]), A = área total da paisagem (500 ha) e U = taxa de especiação na paisagem. Essa igualdade pressupõem que a densidade de unidades de habitat (ou de não habitat) é constante na paisagem. Considerando $DA_{media} = DA_{obs}$, podemos utilizar essa igualdade para obter U a partir do modelo neutro de campo médio (EI) e $\theta$ a partir do modelo neutro de espaço explícito (EE). 


  *m* é a probabilidade de uma morte na 'comunidade local' ser sucedida de um evento de imigração (de movimentação sucedida de colonização e amadurecimento até a idade reprodutiva) de um indivíduos da metacomunidade. Assim, se m = 0.1, então  10% dos indivíduos na amostra (i.e. a 'comunidade local) são imigrantes que chegaram ao acaso da paisagem ao redor (adaptado de Ricklefs 2012). Esse parâmetro descreve a limitação à dispersão no nível da amostra, imaginando uma comunidade local que se relaciona por dispersão com um o conjunto de comunidades locais onde todas podem potencialmente trocar indivíduos (a metacomunidade/paisagem) (Etienne et al. 2007). Chisholm & Lichstein (2009) estabeleceram uma aproximação entre *m* e *d*:
  
$$ m = P_{amostra} d / \pi A_{amostra} $$

Onde $P_{amostra}$ e $A_{amostra}$ são respectivamente o perímetro e área da amostra. Essa aproximação independe da forma da amostra ou da distribuição de probabilidade subjacente a função de dispersão (probabilidade de um indivíduos colonizar um sítio como função da distância do sítio e da planta progenitora). Utilizando apenas amostras contíguas, aproximamos-as como um quadrado na simulação coalescente, assim, podemos simplicar a formula acima considerando que $P_{amostra} = 4 l_{amostra}$ e $A_{amostra} = l_{amostra}^2$, onde $l_{amostra}$ = lado da amostra; e como $A_{amostra} = J / DA_{obs}$:

$$ m = d  (4/ 100 \pi \sqrt{J/DA_{obs}})$$

A variável *d* está descrita na unidade de espaço utilizada para definir $DA_{obs}$. A unidade de espaço utilizada em $DA_{obs} = individuos/ha$ é o héctare (*ha*) = $100^2$ metros, assim, para escrever *d* em metros dividimos por 100, uma vez que $\sqrt{ha} = 100$ metros.   


## Função de dispersão na simulação coalescente ##

A função de dispersão descreve a probabilidade de um indivíduo colonizar um sítio como função da distância do sítio e da planta progenitora. Em geral essa função utiliza uma distribuição de probabilidade para aproximar a função de dispersão (Rosindell et al. 2008). Na simulação coalescente o espaço não é contínuo, ele é descrito como unidade de habitat discreto - onde apenas um indivíduo pode se estabelecer, que podemos aproximar como um quadrado de lado ($l_{cel}$) = $100/ \sqrt{DA_{obs}}$ (unidade de espaço = $metros / \sqrt{individuos}$). Assim, ao utilizar distribuições de probabilidade para aproximar a função de dispersão na simulação coalescente temos que converter a escala da distribuição de probabilidade da escala padrão para a escala da simulação.

A distribuição de probabilidade que utilizamos na função de dispersão foi a distribuição Laplace. A distribuição Laplace, que pode ser entendida como uma distribuição exponencial negativa espelhada,  é descrita por dois parâmetros: $\mu$, parâmetro de localização; e b, parâmetro escalar, que determina a dispersão estatística da distribuição. Considerando que todos os indivíduos na simulação possuem a mesma função de dispersão e na simulação coalescente voltamos no tempo afim de reconstruir a genealogia da comunidade, podemos inverter a função de dispersão e centra-la no sítio vago afim de estimar a localização do indivíduo que será o progenitor daquele indivíduo que ocupou o sítio vago (Rosindell et al. 2008), assim $\mu = 0$. *b* é estimado como a média do desvio absoluto de $\mu$ e portanto pode ser interpretado como a distância média de dispersão (*d* da aproximação de Chisholm & Lichstein 2009). A variância da distribuição Laplace pode ser descrita como: $var = 2b^2$, logo, $b = \sqrt{var}/ \sqrt{2}$;  podemos parametrizar a distribuição pelo desvio padrão ($sd = \sqrt{var}$) e temos que:

$$ b = sd/ \sqrt{2} $$

A unidade de *b* é a dimensão espacial padrão, metros. Como b = d então podemos reescrever a aproximação de Chisholm & Lichstein (2009) em termos do desvio padrão da função de dispersão considerando a distribuição Laplace:

$$ m = 4 sd / 100 \pi \sqrt{2J/DA}) $$
O benefício de parametrizar a função de dispersão em termos de desvio padrão é que fica mais fácil comparar funções de dispersão utilizando outras distribuições de probabilidade na simulação coalescente, como a distribuição normal (Rosindell & Etienne 2011) e uniforme (Campos et al. 2013) [REESCREVER].


### Função de dispersão e chuva de propagulos ###

A chuva de propágulos pode ser entendida como o produto da fecundidade e função de dispersão (Clark et al. 1999). Por conta do pressuposto da equivalência funcional todos os indivíduos produzem o mesmo número de propágulos por unidade de tempo (Hubbell 2001), assim, podemos simular cenários de limitação à dispersão em função da porcentagem de propágulos que permace até determinada distância da planta progenitora. Dessa maneira, não precisamos definir a dispersão em termos de distância *per se* mas em termos de porcentagem de indivíduos que permanecem na área imediata da planta progenitora. Para isso é necessário estabelecer uma distância padrão da planta progenitora e estimar ou definir a porcentagem de indivíduos que se mantêm até esta distância padrão. Como distância padronizamos $l_{cel}$, assim, cada paisagem possui uma distância padrão que depende da densidade observada de indivíduos naquela paisagem. Como porcentagem de indivíduos que se mantêm até essa determinada distância podemos estimar *sd* a partir do parâmetro *m* utilizando a aproximação de Chisholm & Lichstein (2009), partindo do modelo EI, ou informar *a priori* quais as porcentagens de interesse, como no modelo EI.



