---
title: "Paisagens Greg"
author: "Danilo Pereira Mori"
date: "2022-10-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, tidy = FALSE, include = TRUE, warning = FALSE,cache = TRUE,message=FALSE,eval=TRUE)
```

```{r pacotes,eval=TRUE,include=TRUE}
library(ggpubr)
library(imager)
library(cowplot)
library(raster)
library(gridExtra)
library(ggplot2)
library(readr)
library(purrr)
library(stringr)
library(tidyr)
library(plyr)
library(dplyr)
select <- dplyr::select
```



```{r dados}
# dados
df_sitios_greg <- read_csv("./resultados_e_SI/df_Greg_SitesAnoAmostragem.csv") |> 
  mutate(year_bestProxy = as.numeric(year_bestProxy))
df_sitios_greg$year_bestProxy[is.na(df_sitios_greg$year_bestProxy)] <- 2012.5
df_tif <- data.frame(tif.name = list.files(path="./dados_para_iniciar_artigo/paisagens_greg_mapbiomas6/",pattern = ".tif",full.names=T)) |> 
  mutate(SiteCode = str_extract(tif.name,"(?<=\\/\\/).*?(?=_MB6)"),
         type = str_extract(tif.name,"(?<=\\_MB6\\_).*?(?=\\.tif)"),
         across(SiteCode:type,factor)) |> 
  left_join(df_sitios_greg,by="SiteCode") |> mutate(diff_yBestproxy_y2000 = year_bestProxy - 2000) |> 
  filter(type=="natfor")
```

## Ano de Amostragem 2000
### mapbiomas 6 e landsat8 mesmo ano

Em verde os pixels classificados como floresta natural pelo mapbiomas6 ou com cobertura vegetal >= 70 no landsat8



```{r difrenca entre idade das paisagens nula, fig.height=3.75}
# dados
df_plot <- df_tif |> filter(diff_yBestproxy_y2000 == 0)
# funções
# leitura padronizada de rasters
f_dataRaster <- function(path_raster,label){
  raster(path_raster) |> 
    as.data.frame(xy=TRUE) |> 
    drop_na() |> 
    rename(value=3) |> 
    mutate(label = label,
           value = ifelse(value %in% c(0,1),value,value/100),
           value = ifelse(value>=0.7,1,0)) 
}
# gráficos para plotar 
f_ggplotRaster <- function(data){
  ggplot(data) +
  geom_tile(aes(x=x,y=y,fill=value)) +
  scale_fill_gradientn(colours = rev(terrain.colors(10))) +
  coord_cartesian(expand = FALSE) +
  theme_bw() + labs(x="",y="") + theme(legend.position="none") + facet_wrap(~label)
}
# for loop
for(i in 1:nrow(df_plot)){
  df <- df_plot[i,]
  ## rasters individuais
  l_data <- list()
  l_data[[1]] <- f_dataRaster(path_raster = df$tif.name, label = "mapbiomas6")
  v_path.landsat8 <- paste0("./dados_para_iniciar_artigo/paisagens_atualizadas/ref",df$refID,"_NA_",df$ordem,".tif")
  l_data[[2]] <- f_dataRaster(path_raster = v_path.landsat8, label = "landsat8")
  ## gráficos
  l_p <- llply(l_data,f_ggplotRaster)
  # v_top <- paste0(df$SiteCode,", sample year: ",df$year_bestProxy)
  grid.arrange(grobs=l_p,ncol=2,top=df$SiteCode)
}
```

## Padronização dos recortes de paisagem para o formato do Treeco: 800 x 800 pixels

```{r padronizacao dos recortes de paisagem para o formato de TreeCo}
df_tif
# dimensões dos raster
f_rasterDim <- function(tif_path){
  dim(raster(tif_path))
}
doMC::registerDoMC(3)
df_audR <- ldply(df_tif$tif.name,f_rasterDim,.parallel = TRUE)
df_audR |> summary()
#
r_1 <- raster(df_tif$tif.name[1]) |> as.matrix()
teste <- 

r_1 |> dim()
ggplot(r_1) +
  geom_tile(aes(x=x,y=y,fill=value)) +
  scale_fill_gradientn(colours = rev(terrain.colors(10))) +
  coord_cartesian(expand = FALSE) +
  theme_bw() + labs(x="",y="") # + theme(legend.position="none")


mat_raster <- matrix(data = getValues(r_1)/100)
dim(mat_raster) <- dim(r_1)[1:2]
v_remove <- dim(mat_raster) - 800
v_start <- floor(v_remove/2)
v_final <- v_remove - v_start

mat_output <- mat_raster[(v_start[1]+1):(nrow(mat_raster)-v_final[1]),
                         (v_start[2]+1):(ncol(mat_raster)-v_final[2])]
dim(mat_output)
par(mfrow=c(1,2)) 
image(mat_raster)
image(mat_output)
```

