---
title: "Esquemas"
author: "Danilo Pereira Mori"
date: "27/04/2021"
output: pdf_document
editor_options: 
  chunk_output_type: inline
---

# Função de Dispersão Inflada

A massa de probabilidade de uma unidade de matrix ser sorteada como parental é redistribuída para as unidades de habitat remanescente, proporcionalmente à massa de probabilidade descrita pela função de dispersão para aquela distância média de dispersão. A massa de probabilidade redistribuída aumenta quanto mais próximo o habitat vago da matrix, maior a proporção de matrix e menor a limitação de dispersão per capita. 

O sorteio de parentesco na simulação coalescente ocorre pelo sorteio independente de duas distribuições de LaPlace ortogonais. Para exemplificar vou considerar uma distribuição exponencial com origem no habitat vago e seguindo apenas em um sentido para o infinito. 

```{r}
library(rmutil)
library(lamW)
library(tidyverse)
library(plyr)
library(magrittr)
df_resultados <- read.csv(file="/home/danilo/Documentos/artigo_mestrado/1A.P_MOVER/simulacao_codigos_e_resultados/resultados/df_resultados.csv",
                            header = TRUE,as.is=FALSE)[,1:13]
range_d <- df_resultados$d %>% range
# p = 1 (no habitat loss)
#
# tabela com duas colunas: 
## distância média de dispersão per capita
## probabilidade de parentesco

# dados brutos
distance <- seq(-100,100,by = 0.1)
sd <- seq(round(range_d[1],digits = 1), 20, by = 2)
# função
f_dlaplace_range <- function(sd,eixo_x=distance) dlaplace(y=eixo_x,s=sd/sqrt(2))
# dados para gráfico
df_plot <- adply(sd,1,f_dlaplace_range,.id = NULL) %>% t %>% as.data.frame()
names(df_plot) <- as.character(sd)
df_plot$distance <- distance
rownames(df_plot) <- NULL
df_plot %<>% gather(sd, probability, -distance)
df_plot$sd <- as.numeric(df_plot$sd)
# plot
ggplot(df_plot,aes(x=distance,y=probability,color=sd,group=sd)) + 
  geom_line() +
  coord_cartesian(xlim = c(-10,10))
```

