---
title: "Piloto de MNEE em paisagens de 4x4km2"
author: ""
date: '2022-03-19'
output: 
  html_document:
    toc: true
    toc_depth: 5
editor_options: 
  chunk_output_type: inline
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = FALSE, include = TRUE, warning = FALSE,cache = TRUE,message=FALSE,eval=FALSE)
knitr::opts_knit$set(root.dir = "/home/danilo/Documentos/artigo_mestrado/1A.P_MOVER/dados_para_iniciar_artigo")
setwd("/home/danilo/Documentos/artigo_mestrado/1A.P_MOVER/dados_para_iniciar_artigo")
```

```{r pacotes,eval=TRUE,include=TRUE}
library(sads)
library(ggpubr)
library(imager)
library(OpenImageR)
library(cowplot)
library(twosamples)
library(doMC)
library(raster)
library(GUILDS)
library(bbmle)
library(magrittr)
library(gridExtra)
library(ggplot2)
library(readr)
library(purrr)
library(stringr)
library(tidyr)
library(plyr)
library(dplyr)
select <- dplyr::select
```


```{r dados,message=FALSE}
### dados ###
# leitura
df_resultados <- read.csv(file="/home/danilo/Documentos/artigo_mestrado/1A.P_MOVER/simulacao_codigos_e_resultados/resultados/df_resultados.csv",
                            header = TRUE,as.is=FALSE)[,1:13]
# padronização
level_k <- as.character(unique(sort(as.numeric(df_resultados$k),decreasing = TRUE)))
df_resultados$k <- factor(df_resultados$k,levels = level_k)
levels(df_resultados$k)[19] <- "0.1"
# z score
f_z <- function(x){
  m <- base::mean(x,na.rm=FALSE)
  sd <- sd(x,na.rm=FALSE)
  output <- (x-m)/sd
  return(output)
} 
# names(df_resultados)
# str(df_resultados)
df_resultados %<>% mutate(diffS_gamma = diffS_mean + min(diffS_mean)*(-1) + 0.01,
                          modulo_diffS = abs(diffS_mean),
                          log_Sobs=log(S_obs))

df_resultados.z <- as.data.frame(apply(df_resultados[,c("p","Ntotal","log_Sobs","k_1","d_Lplot","d","modulo_diffS")],2,f_z))
names(df_resultados.z) <- sapply(names(df_resultados.z), function(x) paste0(x,".z"))
df_resultados %<>% cbind(.,df_resultados.z) %>% 
  select(-k_1,-k_1.z)
```

Plano:
1) amostrar 30 pontos de uma uniforme de 0 a 1
2) subtrair, para cada ponto sorteado em 1, a proporção de cobertura vegetal observada (coluna 'p')
3) selecionar, para cada ponto sorteado em 1, aquele que obteve menor diferença em 2

```{r}
f_random_byVar <- function(x = df_resultados,
                           column_name = "p", 
                           n_sample = 30, 
                           i_seed = 260320223){
  # amostragem de uma uniforme
  set.seed(i_seed)
  sample_points <- sort(runif(n = n_sample, min = 0, max = 1))
  # encontrar os valores mais próoximos
  df_x <- filter(x,k==levels(x$k)[1],MN=="EE")
  f_index <- function(X=df_x,
                      name=column_name,
                      v_ref){
    which.min(abs(X[[column_name]] - v_ref))
  }
  # remover os sítios repetidos
  v_sites <- df_x[sapply(sample_points,function(y) f_index(v_ref=y)),"SiteCode"] %>% unique
  df_return <- filter(x,SiteCode %in% v_sites,MN=="EE")
  df_return$SiteCode <- factor(df_return$SiteCode)
  return(df_return)
}
df_piloto <- f_random_byVar(x=df_resultados)
# gráficos exploratóritos
# df_piloto %>% 
#   ggplot(aes(x=p,y=S_obs)) + geom_point()
```


